name: Docker Example

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies for testing
        run: npm install

      - name: Test the code
        run: npm test -- --coverage

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: lucadanijspxl
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Dockerfile dynamically
        run: |
          echo "FROM node:18" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY package*.json ./" >> Dockerfile
          echo "RUN npm install --production" >> Dockerfile
          echo "COPY . ." >> Dockerfile
          echo "RUN npm run build" >> Dockerfile
          echo "EXPOSE 5000" >> Dockerfile
          echo "ENV NODE_ENV=development" >> Dockerfile
          echo "CMD [\"node\", \"dist/index.js\"]" >> Dockerfile

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .            # Path context includes all files
          file: ./Dockerfile    # Use the dynamically created Dockerfile
          push: true
          tags: lucadanijspxl/nodejs-demo-app:latest
